### ISSUE TITLE
Integrate Backup Procedure

### ISSUE THREAD

**Issue by Lsquared13** [Eximchain/terraform-aws-quorum-cluster#16]
# Problem
We have written a backup script that can be used to back up chain data to s3 or restore from a previous backup, but it only runs on a completely manual basis.

# Solution
The backup needs to run at least periodically with a cron job or something similar. Ideally, we should also be able to run it in response to a cloudwatch alarm, although that does not block network launch.

We also need a way to run the restoration for every instance simultaneously.

**Comment by Lsquared13** [comment]
We should also regionalize the backups ideally. That would save us money, but also add some complexity.

**Comment by ExcChua** [comment]
Trying to assign to myself...

**Comment by ExcChua** [comment]
I need access to review this backup script. Where is it located?

**Comment by Lsquared13** [comment]
The backup script is here: [backup-chain-data.py](https://github.com/Eximchain/terraform-aws-quorum-cluster/blob/master/packer/instance-scripts/backup-chain-data.py)

You invoke it with either `backup-chain-data.py backup` to do a backup or `backup-chain-data.py restore --block N` where `N` is the block number we would like to restore from. If a backup has not been created for that block number it will fail.

The `backup` argument can take an optional `--force` argument. By default, if you try to make a backup when a backup already exists at that block number, you will get an error. The force option lets you override that.

Both arguments can take an extra `--bucket` argument. Each region has a default bucket for backups, but you can use that argument to force a backup to or restoration from another region's bucket.

**Comment by ExcChua** [comment]
From examining the script, it appears that the script is meant to be run locally on the target node, is this correct?

In order for this script to be automated and run for an entire region (based on my thoughts), it would need exclusive access to the S3 bucket designated as the backup, as well as access to the target node. It would also need to write the name of the node it backup, and the S3 backup bucket it wrote to, to a central file, so that the restoration process can be automated. (For a centralized backup and restore, initiated from a central node)

Alternatively, the backup and restoration process can be distributed by a (sort of) supervisor that reaches out to every node that requires backup, and tells it to start the backup. The supervisor can then also reach out to every node that requires restoration, and tells it to start the restore.

What do you think?

**Comment by Lsquared13** [comment]
Yes, it is meant to be run locally on the target node. My thought was that the integration would come down to how and when it is invoked

"it would need exclusive access to the S3 bucket designated as the backup"

I'm a little confused as to what you're getting at here. The idea was for an entire region to share a backup bucket. Ideally, every so often, one node in each region does a backup, and then if we need to restore, everyone restores from the backup in their region (which wasn't necessarily produced by them).

You can add metadata to make this job easier. Here's a couple of ideas I had on how this might work. You're free to base your solution on one of these things or come up with your own.

- The backup is run on every node by a cronjob. Some sort of locking mechanism (e.g. DynamoDB) is used to ensure only one node per region does the backup. When a node tries to backup and sees another node has taken that task, it starts checking for confirmation that the other node has completed the backup. When it finds confirmation, it stops trying, and if it believes that the other node has crashed, it takes over (It's not a catastrophe if two nodes do backup, it just gets expensive to have all nodes do backup all the time)
- An AWS event (e.g. triggered by a metric tracking time since the last backup) triggers a Lambda function that picks a node and invokes its backup procedure

**Comment by ExcChua** [comment]
The exclusive access mechanism I was thinking is the same as your locking mechanism, in order to ensure that only one node accesses the S3 bucket exclusively.

Thanks for your ideas. I'll think about it and begin implementing this as soon as possible.

**Comment by Lsquared13** [comment]
Remember we will eventually want to be able to trigger this with cloudwatch alarms as well, so consider that in your design. For example, my second suggestion above gets that for free, while the first would require you to build it in, so if you go with that you should have a plan in place to build cloudwatch support.

**Comment by ExcChua** [comment]
With the -mode=aws extension created for the CreateConfig portion of SoftwareUpgrade, the restoration process is now a matter of the following:

1. running CreateConfig -mode=aws with the proper filter to extract a certain NetworkId's instances into a json output file.

1. running CreateConfig -mode=cli with a template file, and the input json from the above -mode=aws output, causing a list of IP addresses to be output.

1.  A bash script that reads the IP addresses in the above step, SSH into all the nodes, and execute the backup-chain-data.py script to restore the backup.

Please share how one decides that a node will be restored. Under what circumstances?

Also, it appears backup and restore will only be run on Quorum nodes, is this correct?

**Comment by Lsquared13** [comment]
Yes, backup and restore is only run on quorum nodes. We may end up needing to build backup into our single node as well.

We'll probably be deciding to restore an entire chain at once in an emergency, for example if the chain stops. It will be a manual decision.

The backup on the other hand will be partially automated.
