### ISSUE TITLE
Add Elastic IPs to Observers (Optionally)

### ISSUE THREAD

**Issue by Lsquared13** [Eximchain/terraform-aws-quorum-cluster#49]
Since we plan on having users connect through observer nodes, they should optionally have Elastic IPs associated with them, similarly to what we did for bootnodes.

**Comment by john-osullivan** [comment]
For the sake of finding things more easily later, here's the PR where I did this same work for bootnodes: https://github.com/Eximchain/terraform-aws-quorum-cluster/pull/29/files 

Essentially, I need to:
1) Add a setting at the top level
2) Propagate it down through the regions
3) Modify the init script to run `ec2 associate-address` with the appropriate EIP on startup
